### PR TITLE
Multiple logos added 

### PR DESCRIPTION
**Pull request by Tushar98644**

### CODE REVIEW

**Comment by Tushar98644** [comment]
Screenshot 2022-12-06 at 12 59 07 AM

**Comment by Tushar98644** [comment]
Screenshot 2022-12-06 at 12 55 39 AM

**Comment by Tushar98644** [comment]
Screenshot 2022-12-06 at 12 50 56 AM

**Comment by Tushar98644** [comment]
@aakriti7x7  Do i need to make changes for the logo?

**Comment by prathamiitp** [comment]
> @aakriti7x7 Do i need to make changes for the logo?

this is an open issue, you submit more designs
the best design in the last week will be selected.

I will suggest try something that signify tinkering, engineering or something related.

**Pull request merged**
